"""empty message

Revision ID: 225764500156
Revises: 365800eb53d3
Create Date: 2023-04-13 09:28:28.772054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225764500156'
down_revision = '365800eb53d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate_state', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('plate_style', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plate_style')
        batch_op.drop_column('plate_state')

    # ### end Alembic commands ###
