"""Make plate unique

Revision ID: 3304dc08eee3
Revises: bac40afda462
Create Date: 2022-11-15 09:09:09.162938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3304dc08eee3'
down_revision = 'bac40afda462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_plate', ['plate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_plate', type_='unique')

    # ### end Alembic commands ###
