"""add location field to user

Revision ID: 365800eb53d3
Revises: fba89224a545
Create Date: 2022-12-02 09:03:45.799393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365800eb53d3'
down_revision = 'fba89224a545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
